### ISSUE TITLE
arkmanager update corrupts install

### ISSUE THREAD

**Issue by PokeyOats** [arkmanager/ark-server-tools#794] opened 2017-06-02 08:58 UTC
Good Day all,

I'm having a situation where when I do an arkmanager update, if there is an update, it completely corrupts the install.

I am having to rectify this by doing a steamcmd validate on the app_update.

Can anyone begin to advise me as to what information I can share to rectify this problem?

**Comment by klightspeed** [comment] 2017-06-02 21:28
Are you using a staging directory?  If yes, please try deleting that staging directory and attempting an update.

**Comment by PokeyOats** [comment] 2017-06-05 22:41
Good Day,

Thank you so much for this suggestion.

I deleted the staging directory and fortunately there was an update, which it downloaded, applied and it corrupted the install again. :(

I am having to use steamcmd, force install dir and validate to repair after arkmanager attempts to update.

This is the result after every update

Running command 'run' for instance 'main'
2017-06-02 21:22:01: start
2017-06-02 21:22:01: Running /home/ark/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=WOPR\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=Gulf4Admin\!\?MaxPlayers=70\?AllowThirdPersonPlayer=true\?MapPlayerLocation=true\?listen -server -log
2017-06-02 21:22:01: Server PID: 7409
Using binned.
4.5.1-0+UE4 7038 3077 402 7
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
EngineCrashHandler: Signal=11
/usr/local/bin/arkmanager: line 1028:  7409 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2017-06-02 21:22:27: Bad PID ''; expected '7409'
2017-06-02 21:22:27: exited with status 0

**Comment by BigMikJ** [comment] 2018-02-11 00:18
I'm having the same issue. Log is not giving me any clue as to why the server won't start.

start
Running /app_data/steam/ARK/theIsland/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?Port=7776\?QueryPort=27015\?GameModIds=731604991\,1184731864\,821530042\,868812923\,751650026\,793605978\,889745138\?MaxPlayers=15\?RCONEnabled=True\?RCONPort=27020\?ServerAdminPassword=########\?ServerPassword=########\?listen -NoTransferFromFiltering -ClusterDirOverride=/app_data/steam/ARK/clusters -clusterid=nukegamingclst
Server PID: 83564
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:C:\SVN_Ark\Engine\Source\Runtime\Core\Private\Linux\LinuxPlatformProcess.cpp] [Line: 652]
FLinuxPlatformProcess::WaitForProc: waitid for pid -1 failed (errno=22, Invalid argument)
Signal 11 caught.
/usr/local/bin/arkmanager: line 1096: 83564 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
Bad PID ''; expected '83564'
exited with status 0

**Comment by klightspeed** [comment] 2018-02-11 03:29
@BigMikJ your issue is a duplicate of #545

**Comment by BigMikJ** [comment] 2018-02-11 19:48
@klightspeed Your solution worked. Even when I start a new world with no mods, still need the SteamCMD dir copied into the ThirdParty folder. The servers are starting now, but maybe you should alter your script to copy the steamCMD dir everytime. Thanks.

**Comment by klightspeed** [comment] 2018-02-11 22:40
That sounds like either Wildcard has made `-automanagedmods` enabled by default, or you have a config line in `GameUserSettings.ini` that enables `automanagedmods`.

**Closed** 2020-08-17 22:07 UTC
Labels: Time Out
